### ISSUE TITLE
Add "labels" to logical networks

### ISSUE THREAD

**Issue by lghamie** [oVirt/ovirt-ansible#101]
When creating networks via oVirt API I can add labels to them(for auto host-placement), which I think I cant with ovirt-ansible.

Am I wrong or is it impossible to do that right now?

**Comment by machacekondra** [comment]
Currently, we support only to assign label to interface/bond on the host, not to create the label and assign it to logical network. So no it's not possible, but we will add it in future.

**Comment by lghamie** [comment]
that's ok. any estimated date for this?

**Comment by machacekondra** [comment]
It's a simple patch, so I think we can get it in two weeks. But in upstream Ansible it will be in 2.5, as 2.4 was released recently and they don't accept new parameters to modules for z-stream releases.

**Comment by machacekondra** [comment]
Need a rebase on top of: https://github.com/ansible/ansible/pull/31517

**Comment by machacekondra** [comment]
Moved to: https://github.com/oVirt/ovirt-ansible-infra/issues/21
