### ISSUE TITLE
[ovirt-cluster-ugprade] more waiting/another try for host status if in non-responsive after upgrade

### ISSUE THREAD

**Issue by jirib** [oVirt/ovirt-ansible#103]
while using ovirt-cluster-ugprade a host was for a while in non-responsive state after successful upgrade and it made task fail. please implement a var to wait a little bit or make another check for state so the task does not fail (the host was Up when I check it in admin portal).

**Comment by machacekondra** [comment]
We need rebase on top of: https://github.com/ansible/ansible/pull/32123
Or wait for Ansible 2.4.2 release.

**Comment by machacekondra** [comment]
Moved to: https://github.com/oVirt/ovirt-ansible-cluster-upgrade/issues/11
