### ISSUE TITLE
[ovirt-cluster-upgrade] a solution for non auto-migratable vms

### ISSUE THREAD

**Issue by jirib** [oVirt/ovirt-ansible#104]
HE VM is non auto-migratable and thus when using ovirt-cluster-upgrade it skips host which has update if the host hosts HE VM. Please make a knob to migrate such VMs so we can use the role for upgrade which have HE VM.

**Comment by machacekondra** [comment]
@mwperina I think we should add new variable called `manual_vm_migration` or similar, which will migrate all VMs which can be migrated only manually. I would add default value to `false` to make it safe.

**Comment by mwperina** [comment]
What's so different on HE VM? AFAIK when you move host, which HE VM is running on, to Maintenance, then HE VM is automatically migrated. Or has something changed recently?

**Comment by machacekondra** [comment]
It'd allowed to be migrated only manually.

**Comment by mgoldboi** [comment]
I have discussed the HE item with MartinS, according to him, a maintenance action on the host should put the HE on local maintenance and perform migration. please check it up with him.

**Comment by machacekondra** [comment]
Moved to: https://github.com/oVirt/ovirt-ansible-cluster-upgrade/issues/10
