### ISSUE TITLE
Split roles into their own repos for use with Ansible Galaxy.

### ISSUE THREAD

**Issue by wtcross** [oVirt/ovirt-ansible#107]
Right now the way Ansible Galaxy is being used is defeating its purpose. The intent of this project is to allow for creating a `<project-root>/roles/requirements.yml`[1] file that specifies dependencies. The Ansible Galaxy CLI can then be used to download roles to the project and have them loaded. If using Tower, then roles will automatically be downloaded into the `<project-root>/roles/` directory.

The current issue is that if I install the `ovirt.ovirt-ansible-roles` role via Ansible Galaxy it is not automatically loadable from the project. There are some workarounds for Ansible, but it basically prevents this from working with Tower.

*Proposed Solution*
Let's create a repo for each of the roles used by this project. Then a `requirements.yml` file can be created in the `roles/` directory of this project, which specifies dependency on each of the roles. This would allow for a user to also put those roles in their own `requirements.yml` file.

[1] http://docs.ansible.com/ansible/latest/galaxy.html#installing-multiple-roles-from-a-file

**Comment by wtcross** [comment]
I'm working on a project to automate installing RHHI that will depend on the roles in this project as well as those in the gdeploy project. Right now I'm going to have to work around the fact that the roles are packaged like they are.

More than happy to help wire all this together. I just don't have permission to submit a PR involving creating multiple repos. :)

**Comment by wtcross** [comment]
An added benefit would be role-specific versioning.

**Comment by mykaul** [comment]
@wtcross - is using them from RPM is a reasonable workaround?

**Comment by wtcross** [comment]
That's the workaround I'm going to use, but would prefer an Ansible Galaxy specific solution. That way the community could use the roles even if they are running on a distro that doesn't use yum, like Debian, Ubuntu, Arch Linux, etc.

**Comment by wtcross** [comment]
Another issue with using RPM is that it won't be as easy to set a specific version of the roles that I want to depend on.

**Comment by mwperina** [comment]
Several comments:

1. There roles are part of oVirt (and downstream RHV) project and as such releasing as RPM is primary distribution channel
2. Currently we have 2 release branches: 1.0.z which is part of oVirt/RHV 4.1 and 1.1.z which will be part of oVirt/RHV 4.2. This means that we always verify all roles with specific release, we don't want to add burden of splitting the roles and move dependency management to each role
3. For now we have 20 roles and we are preparing others, so splitting one role per repo will add huge load not only to repo management, but also each role would have to be in separate RPM and that would add even more load to us
4. We have looked at other similar projects and both OpenShift [1] and OpenStack [2] also uses one repository per multiple roles
5. We have described manual steps for Ansible Galaxy installation in README.md [3]

Also oVirt 4.2 beta release is close, so even if we agree to splitting I highly doubt we will be able to finish all necessary changes in time.

So if Ansible Galaxy installation is really necessary, then let's try to find solution which will fix that issue without spliting.

Thanks

Martin

[1] https://github.com/openshift/openshift-ansible
[2] https://github.com/openstack/openstack-ansible
[3] https://github.com/ovirt/ovirt-ansible#installing-using-galaxy

**Comment by wtcross** [comment]
I'm working on a project right now to automate installing/configuring Red Hat Hyperconverged Infrastructure with Ansible, just in case RHHI didn't make sense earlier. It involves content from both oVirt and Gluster.

Splitting roles out into their own repositories can be very painless if you have proper automation in place. That said, writing these scripts isn't exactly trivial. The OpenStack project is splitting their roles out into separate repositories [1]. They have some scripting in place to keep their master repo and the role repos in sync. I'm not a collaborator on the project, but I know there is a script for updating roles [2] and a role requirements file [2], which seem to indicate that they are managing roles upstream. There is an obvious difference between the OpenStack roles and the ones in this project, though. The OpenStack roles are each focused on setting up a specific service, for the most part.

My ask is that roles be split out into multiple repositories so this content is more reusable in the Ansible ecosystem, just like the OpenStack project has done. We can defer this discussion to a future date if you like, but if RHHI is going to have an automated installer it would be nice to avoid working around how Galaxy works and take advantage of individual role reuse.

[1] https://github.com/search?utf8=%E2%9C%93&q=org%3Aopenstack+openstack-ansible&type=Repositories
[2] https://github.com/openstack/openstack-ansible/blob/master/scripts/sources-branch-updater-lib.sh
[3] https://github.com/openstack/openstack-ansible/blob/master/ansible-role-requirements.yml

**Comment by machacekondra** [comment]
The roles are now in following git repos:

* [oVirt.cluster-upgrade]
* [oVirt.disaster-recovery]
* [oVirt.engine-setup]
* [oVirt.infra]
* [oVirt.image-template]
* [oVirt.manageiq]
* [oVirt.repositories]
* [oVirt.vm-infra]

[oVirt.infra]: https://github.com/oVirt/ovirt-ansible-infra/blob/master/README.md
[oVirt.image-template]: https://github.com/oVirt/ovirt-ansible-image-template/blob/master/README.md
[oVirt.vm-infra]: https://github.com/oVirt/ovirt-ansible-vm-infra/blob/master/README.md 
[oVirt.cluster-upgrade]: https://github.com/oVirt/ovirt-ansible-cluster-upgrade/blob/master/README.md
[oVirt.manageiq]: https://github.com/oVirt/ovirt-ansible-manageiq/blob/master/README.md
[Creating Reusable Playbooks]: http://docs.ansible.com/ansible/latest/playbooks_reuse.html
[oVirt Deployment Options]: https://www.ovirt.org/download/
[Galaxy]: https://galaxy.ansible.com/
[oVirt organization]: https://galaxy.ansible.com/oVirt/
[oVirt.disaster-recovery]: https://github.com/oVirt/ovirt-ansible-disaster-recovery/blob/master/README.md
[oVirt.engine-setup]: https://github.com/oVirt/ovirt-ansible-engine-setup/blob/master/README.md
[oVirt.repositories]: https://github.com/oVirt/ovirt-ansible-repositories/blob/master/README.md
