### ISSUE TITLE
Start/stop pinned VMs before/after the upgrade of the host, not of the whole cluster

### ISSUE THREAD

**Issue by machacekondra** [oVirt/ovirt-ansible#117]
Currently we stop pinned VMs before the cluster upgrade not the specific host upgrade, where the VM is pinned. We should just stop the VM when we are upgrading the host not the cluster, so the VM is quickly up.

**Comment by mykaul** [comment]
As well as bring those VMs up when the host is back up, and not at the end of the whole upgrade process.

**Comment by machacekondra** [comment]
@mykaul The problem is, that during cluster upgrade we use 'ClusterInMaintenance' policy, so only HA VMs can be started. So if VM won't be HA we can start it at the end, is that OK?

**Comment by machacekondra** [comment]
cc @mwperina

**Comment by mykaul** [comment]
It's better than what we have today. It's not optimal, but I think (in 4.2?) you can have a pinned VM set as HA too.

**Comment by machacekondra** [comment]
Moved to: https://github.com/oVirt/ovirt-ansible-cluster-upgrade/issues/9
