### ISSUE TITLE
ovirt-clusters default migration policy (post_copy) for development profile gives an error

### ISSUE THREAD

**Issue by mgoldboi** [oVirt/ovirt-ansible#120]
failed: [localhost] (item={u'profile': u'development', u'name': u'test', u'cpu_type': u'Intel Conroe Family'}) => {"failed": true, "item": {"cpu_type": "Intel Conroe Family", "name": "test", "profile": "development"}, "msg": "value of migration_policy must be one of: legacy,minimal_downtime,suspend_workload, got: post_copy"}

**Comment by machacekondra** [comment]
@mgoldboi this happens on master with Ansible 2.3.2? On master we now depend on Ansible 2.4
