### ISSUE TITLE
ManageIQ vars are located in role default 

### ISSUE THREAD

**Issue by mgoldboi** [oVirt/ovirt-ansible#121]
defaults are deep into the role structure and the user shouldn't change it, right?
should we extract those vars to a var_file or to the playbook example?

Thanks.

**Comment by machacekondra** [comment]
@mgoldboi I think most the vars in this role are meant to be changed. Which variables do you think shouldn't be changed?

cc @mwperina

**Comment by machacekondra** [comment]
Moved to: https://github.com/oVirt/ovirt-ansible-manageiq/issues/12
