### ISSUE TITLE
Document which role version support which oVirt engine version

### ISSUE THREAD

**Issue by machacekondra** [oVirt/ovirt-ansible#143]
Currently we support following:

 - 1.1.x ansible role s oVirt >= 4.1
 - 1.2.x ansible role s oVirt >= 4.2
 - 1.3.x ansible role s oVirt >= 4.3

We need to document it.

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
