### ISSUE TITLE
Problem with installing role oVirt.repositories and oVirt.engine-setup from ansible-galaxy

### ISSUE THREAD

**Issue by pkubica** [oVirt/ovirt-ansible#145]
due to bug https://github.com/ansible/galaxy/issues/149
now user must install roles from galaxy with sudo command, this now cause problem when using the role repositories and engine-setup.
second thing, it could cause some problems in the future so role should be installed within the same path

[pkubica@localhost]$ sudo ansible-galaxy install oVirt.repositories
- changing role oVirt.repositories from 1.1.0 to unspecified
- downloading role 'repositories', owned by oVirt
- downloading role from https://github.com/oVirt/ovirt-ansible-repositories/archive/1.1.0.tar.gz
- extracting oVirt.repositories to **/root/.ansible/roles/oVirt.repositories**
- oVirt.repositories (1.1.0) was installed successfully

[pkubica@localhost]$ sudo ansible-galaxy install oVirt.vm-infra
- changing role oVirt.vm-infra from 1.1.3 to unspecified
- downloading role 'vm-infra', owned by oVirt
- downloading role from https://github.com/oVirt/ovirt-ansible-vm-infra/archive/1.1.3.tar.gz
- extracting oVirt.vm-infra to **/etc/ansible/roles/oVirt.vm-infra**
- oVirt.vm-infra (1.1.3) was installed successfully

$ansible --version
ansible 2.4.2.0
  config file = /home/pkubica/redhat/ansible/roles/build/ansible.cfg
  configured module search path = [u'/home/pkubica/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
