### ISSUE TITLE
oVirt.hosted-engine-setup is not available in ansible galaxy

### ISSUE THREAD

**Issue by petr-balogh** [oVirt/ovirt-ansible#161]
From some reason oVirt.hosted-engine-setup is not released in galaxy.
ERROR:
16:21:13 - downloading role 'hosted-engine-setup', owned by oVirt
16:21:14  [WARNING]: - oVirt.hosted-engine-setup was NOT installed successfully: -
16:21:14 sorry, oVirt.hosted-engine-setup was not found on https://galaxy.ansible.com.

**Comment by petr-balogh** [comment]
same for oVirt.shutdown-env

**Comment by machacekondra** [comment]
@tiraboschi Can you please rename those to using `_` instead of `-`, or ask Galaxy maintainers to rename those roles for you?

**Comment by tiraboschi** [comment]
@irosenzw can you please take a look?

**Comment by GaLaKtIkUs** [comment]
> @tiraboschi Can you please rename those to using `_` instead of `-`, or ask Galaxy maintainers to rename those roles for you?

Can you please provide a more detailed description of the procedure to follow?

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
