### ISSUE TITLE
Make all roles to be 5.0/5.0 score

### ISSUE THREAD

**Issue by machacekondra** [oVirt/ovirt-ansible#168]
Go over all roles and make their score 5.0 as per:

 https://galaxy.ansible.com/docs/contributing/content_scoring.html

**Comment by machacekondra** [comment]
@mnecas Can you please take a look?

cc @mwperina

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
