### ISSUE TITLE
Role naming does not respect case sensitivity

### ISSUE THREAD

**Issue by mkowalski** [oVirt/ovirt-ansible#171]
As of today executing `$ ansible-galaxy install oVirt.ovirt-ansible-roles` causes the following folder structure to appear

```
$ ls | grep -i ovirt
oVirt.cluster-upgrade
oVirt.disaster-recovery
oVirt.engine-setup
oVirt.image-template
oVirt.infra
oVirt.manageiq
ovirt.ovirt-ansible-roles
oVirt.repositories
oVirt.v2v-conversion-host
oVirt.vm-infra
```

However, the child roles reference to all the others using strictly lowercase syntax, what causes issues as below

```
The error appears to be in '/home/kmateusz/.ansible/roles/oVirt.infra/tasks/create_infra.yml': line 4, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  import_role:
    name: "ovirt.infra/roles/ovirt.mac-pools"
          ^ here
```
What is a model solution in here? Should I really manually rename directories under `~/.ansible` or should I recursively `sed` across all the `import_role` and make them aware of the upper/lowercase?

**Comment by machacekondra** [comment]
Thanks for reporting. I've renamed the dependency names. So if you install version 1.1.7, it will actually install all roles lower case and it will work properly.
