### ISSUE TITLE
plans to use collections

### ISSUE THREAD

**Issue by aoyawale** [oVirt/ovirt-ansible#175]
was wondering if there's any plans to use ansible collections.

**Comment by machacekondra** [comment]
Yes, we plan. We are waiting on more information how to migrate to the collections.

@mwperina @mnecas

**Comment by aoyawale** [comment]
awesome! I been using the vm create role a lot and a freeipa role maintain by their team. They have added theirs as a collection.

**Comment by mnecas** [comment]
I migrated all modules here https://github.com/ovirt/ovirt-ansible-collection and put it to ansible-galaxy. On RPM version I'm still working.
