### ISSUE TITLE
How do we enable WinRM on a Windows VM running on Red Hat Virtualization via Ansible ?

### ISSUE THREAD

**Issue by shamaljayalath** [oVirt/ovirt-ansible#189]
Hi Team, We have a customer looking at migrating from VMware to Red Hat virtualization and wanted to use Ansible as their automation platform.

The issue is when provisioning Windows VM on RHV using Windows template via Ansible, for Ansible to communicate further with Guest OS (Windows) WinRM needs to be enabled.

With VMware we used the "vmware_vm_shell" to talk to Windows guest and enabled WinRM and upon enabling WinRM Ansible could connect to the guest OS and carry on with the rest of the configuration.

name: Enable WinRM to be used with Ansible
local_action:
module: vmware_vm_shell
hostname: "{{ vcenter_server }}"
username: Administrator@vsphere.local
password: "{{ vsphere_password }}"
vm_username: Administrator
vm_password: "{{ vm_password }}"
vm_id: "{{ vm_name }}"
vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
vm_shell_args: "{{ item }}"
with_items:
- '-command "& {Set-ExecutionPolicy Unrestricted}"'
- '-command "& {Invoke-Expression ((New-Object System.Net.Webclient).DownloadString("https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1\"))}"'
- '-command "& {Set-ExecutionPolicy RemoteSigned}"'
Given "vmware_vm_shell" is not applicable on RHV, how do we enable WinRM during the provisioning of new VM ? Enabling WinRM on the template is less desirable and we would like to configure on the fly.

Having module something similar to "vmware_vm_shell" for RHV would also give us alternative ways to connect to VM if connecting via WinRM/SSH is not an option due to security.

How do you recommend enabling WinRM on a Windows VM during running on Red Hat Virtualization via Ansible playbook?

**Comment by mnecas** [comment]
Hi @shamaljayalath,
how about using Sysprep[1] custom_script[2]?
It is missing in the docs but the functionality is there
[1] https://docs.ansible.com/ansible/latest/modules/ovirt_vm_module.html#parameter-sysprep
[2] https://github.com/oVirt/ovirt-ansible-collection/pull/52

**Comment by shamaljayalath** [comment]
Hi @mnecas, I appreciate your prompt reply to this. Since the option is documented well, I'm uncertain of the usage of the custom_script under Sysprep.

Would it be something like this?

ovirt_vm:
    name: windows2012R2_AD
    template: windows2012R2
    cluster: Default
    memory: 3GiB
    high_availability: true
    sysprep:
      host_name: windowsad.example.com
      user_name: Administrator
      root_password: SuperPassword123
      custom_script:'c:\windows\system32\windowspowershell\v1.0\enable_winrm_script.ps1'

Could you please confirm if the above usage of the custom_script under Sysprep is correct ?

If you could provide me with some direction, I'm happy to give this a go and report the results.

Thanks again.

**Comment by shamaljayalath** [comment]
Or would it be something like this : 

ovirt_vm:
name: windows2012R2_AD
template: windows2012R2
cluster: Default
memory: 3GiB
high_availability: true
sysprep:
host_name: windowsad.example.com
user_name: Administrator
root_password: SuperPassword123
custom_script: 
           path: 'c:\windows\system32\windowspowershell\v1.0\enable_winrm_script.ps1'

Any pointers are much appreciated :)

**Comment by mnecas** [comment]
I think the first option but I'm also not sure for 100%. You can create some small cmd file which would for example just create some dir so you would know that it is working. 
This might help [2].
But to get the sysprep working you need to update the template image [1].
[1] https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/sysprep--generalize--a-windows-installation
[2] https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/add-a-custom-script-to-windows-setup

**Comment by mnecas** [comment]
@shamaljayalath any updates with the sysprep?

**Comment by shamaljayalath** [comment]
Hi @mnecas, Its for one of the customers I work with so I had to wait for him to come back..

Since he is not very savvy with Linux I could not go back to him as I did not have anything very specific..

We noticed we have the following options from within Windows sysprep.

WinRM can be enabled during sysprep process if necessary. Some information can be found via the link below:
https://github.com/aelrayess/AnsibleSysprep

We can call the powershell script that enables WinRM from within setupcomplete.cmd that gets executed soon after sysprep.

You can see a similar example here: https://github.com/techthoughts2/NanoServer

In our case, we just need to replace nanosetup.ps1 with the name of the powershell that enables Winrm for us (ConfigureRemotingForAnsible.ps1).
 https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1



I think once we get the document in order with some examples, this will be a very useful setting to have. Please see if you can add an example at the bottom of the page so it will be adopted correctly by the customers.

**Comment by shamaljayalath** [comment]
@mnecas - I appreciate your help in this.

**Comment by mnecas** [comment]
Yeah happy to help but I don't understand what examples I should add.
I'm missing something. Could you please ping me at mnecas@redhat.com.

**Comment by shamaljayalath** [comment]
Hi @mnecas - Unfortunately I did not go down the path of using custom_script thus I do not have a Ansible code I can share with you as an example that can go into the documentation.

I have another issue. I will raise another ticket for that. Please feel free to archive this one.

Thanks,
