### ISSUE TITLE
installation behind an http proxy server

### ISSUE THREAD

**Issue by sunnymoon** [oVirt/ovirt-ansible#190]
When installing behind a proxy server either from cockpit or from command line the script fails:
1. To download the first images: this can be solved by exporting http_proxy, https_proxy and no_proxy (don't forget to include all internal network CIDRs) and using the command line installation 
2. To download rpms and files inside the hosted-engine local VM: we hacked it by passing several environment: variables to tasks and also changing yum.conf with lineinfile task inside the VM tasks (next to filling the hosts file with external VM ip)

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
