### ISSUE TITLE
consider the ability to add more than one datacenter

### ISSUE THREAD

**Issue by tareqalayan** [oVirt/ovirt-ansible#25]
Currently the ovirt-dataceneters role expects to deal with one data center.
to be more salable, we need maybe to consider to have a list of datacenters.

**Comment by machacekondra** [comment]
I beleive it would be nicer to implement this on Ansible side, the tracking issues:

https://github.com/ansible/ansible/issues/24921

**Comment by machacekondra** [comment]
Moved to: https://github.com/oVirt/ovirt-ansible-infra/issues/19
