### ISSUE TITLE
ovirt-clusters memory policy is not a memory policy

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-ansible#44]
Server/Desktop is not a policy but a performance preset. Wording should be changed prior to inclusion in 4.1.z

**Comment by machacekondra** [comment]
@michalskrivanek @mwperina This is how it's named also in our API. I can add a new alias, but I wouldn't remove the old one, so we don't brake backward compatibility. How should I name it, `memory_optimization` ?
