### ISSUE TITLE
ovirt-image-template: missing jmespath-terminal

### ISSUE THREAD

**Issue by pkubica** [oVirt/ovirt-ansible#59]
Description of problem:
TASK [ovirt-image-template : Find data domain] ********************************************************************************************************************************************************************
fatal: [**FILTERED**]: FAILED! => {"failed": true, "msg": "You need to install \"jmespath\" prior to running json_query filter"}

TASK [ovirt-image-template : Remove vm] ***************************************************************************************************************************************************************************
fatal: [**FILTERED**]: FAILED! => {"failed": true, "msg": "The conditional check 'ovirt_templates | length == 0' failed. The error was: error while evaluating conditional (ovirt_templates | length == 0): 'ovirt_templates' is undefined\n\nThe error appears to have been in '/usr/share/ansible/roles/ovirt-image-template/tasks/main.yml': line 104, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  always:\n    - name: Remove vm\n      ^ here\n"}

missing https://pypi.python.org/pypi/jmespath-terminal/0.2.1
install it solve this issue

Version-Release number of selected component (if applicable):
ansible-2.3.1.0-3.el7.noarch
ovirt-ansible-roles-1.0.1-1.el7ev.noarch
python-ovirt-engine-sdk4-4.1.6-1.el7ev.x86_64
ovirt-engine-restapi-4.1.5.2-0.1.el7.noarch
ovirt-engine-4.1.5.2-0.1.el7.noarch

**Comment by machacekondra** [comment]
Closed via #58
