### ISSUE TITLE
ovirt-vm-infra: state == absent requires full set of profile parameters

### ISSUE THREAD

**Issue by KKoukiou** [oVirt/ovirt-ansible#77]
https://github.com/oVirt/ovirt-ansible/blob/2783502690f8825d609a66e86ab2f7da41348a5d/roles/ovirt-vm-infra/tasks/main.yml#L19-L23

when trying to remove managed VMs it fails on missing parameters in `profile` dictionary.

Why is it necessary to provide this information to remove VMs ?

**Comment by machacekondra** [comment]
@tareqalayan AFAIK you've added the `state` param, can you take a look?

**Comment by tareqalayan** [comment]
I added the state parameter because if i don't pass it, the VM will go into running state.
While i want to create this VM from a template and the disk to be on a specific storage domain. 
So i have to create the VM and set the state to be stopped. Otherwise it will be on running state and the disk will be on the a storage that was picked randomly and not be me.

**Comment by machacekondra** [comment]
Ah, ok this is actually already reported here:

 https://bugzilla.redhat.com/show_bug.cgi?id=1489893

I will fix it.

**Comment by tareqalayan** [comment]
@KKoukiou  this will break us. for example for the CFME template we would like to overide the core and memory no? 

@machacekondra  can the behaviour be that if core and memory not stated it will be taken from template otherwise it will be taken from the module params?

**Comment by KKoukiou** [comment]
@tareqalayan I opened issue in order to not expect all these parameters in the case that `state == absent`... 
But with a second look, I think this role is supposed to populate envs in fact, not clean them up, so I would just add it to documentation of role, that absent is not really suported, and leave behavior like this.

Regarding the default values of cores and memory, I think we can adjust our description files.

**Comment by machacekondra** [comment]
In #80 I've changed the documentation and listed only states `stopped`, `present` and `running`.

**Comment by machacekondra** [comment]
But it will work for you if you will not pass any `tag` and `wait_for_ip=false`.

**Comment by KKoukiou** [comment]
@machacekondra I am ok with it, thanks!
